version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: wallet_db
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    container_name: wallet_app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT